spring.application.name=campaign
server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:secret@localhost:27017/campaign?authSource=admin}
spring.data.mongodb.auto-index-creation=true
